version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: yearly
    timezone: Europe/London
  ignore:
    - dependency-name: "Microsoft.Extensions.DependencyInjection.Abstractions"
    - dependency-name: "Microsoft.Extensions.Logging.Abstractions"
