//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinCostello.SqlLocalDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MartinCostello.SqlLocalDb.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created named instance {InstanceName} of SQL LocalDB with version {InstanceVersion}..
        /// </summary>
        internal static string ILoggerExtensions_CreatedInstanceFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_CreatedInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating named instance {InstanceName} of SQL LocalDB with version {InstanceVersion}..
        /// </summary>
        internal static string ILoggerExtensions_CreatingInstanceFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_CreatingInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted file(s) for SQL LocalDB instance {InstanceName} from {InstanceFilesPath}..
        /// </summary>
        internal static string ILoggerExtensions_DeletedInstanceFilesFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_DeletedInstanceFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted named instance {InstanceName} of SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_DeletedInstanceFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_DeletedInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB instance {InstanceName} could not be deleted as it is currently in use..
        /// </summary>
        internal static string ILoggerExtensions_DeleteFailedAsInUseFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_DeleteFailedAsInUseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete SQL LocalDB instance {InstanceName} with HRESULT {HResult}..
        /// </summary>
        internal static string ILoggerExtensions_DeleteFailedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_DeleteFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting named instance {InstanceName} of SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_DeletingFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_DeletingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file(s) for SQL LocalDB instance {InstanceName} from {InstanceFilesPath}..
        /// </summary>
        internal static string ILoggerExtensions_DeletingInstanceFilesFailedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_DeletingInstanceFilesFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file(s) for SQL LocalDB instance {InstanceName} from {InstanceFilesPath}..
        /// </summary>
        internal static string ILoggerExtensions_DeletingInstanceFilesFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_DeletingInstanceFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB function {LocalDBFunctionName} could not be found..
        /// </summary>
        internal static string ILoggerExtensions_FunctionNotFoundFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_FunctionNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining instance names for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_GetInstances {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GetInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining information for SQL LocalDB instance {InstanceName}..
        /// </summary>
        internal static string ILoggerExtensions_GettingInfoFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GettingInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining version information for SQL LocalDB version {Version}..
        /// </summary>
        internal static string ILoggerExtensions_GetVersionInfoFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GetVersionInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining versions for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_GetVersions {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GetVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained information for SQL LocalDB instance {InstanceName}..
        /// </summary>
        internal static string ILoggerExtensions_GotInfoFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GotInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained {InstanceCount} instance names for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_GotInstancesFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GotInstancesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained version information for SQL LocalDB version {Version}..
        /// </summary>
        internal static string ILoggerExtensions_GotVersionInfoFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GotVersionInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained {VersionCount} versions for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_GotVersionsFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_GotVersionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL LocalDB instance {InstanceName} cannot be found so was not deleted..
        /// </summary>
        internal static string ILoggerExtensions_InstanceDoesNotExistFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_InstanceDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current Language Id {LanguageId} is not recognized by SQL LocalDB. Use a valid Windows Locale ID (LCID) or set the value to zero to use the Windows defaults..
        /// </summary>
        internal static string ILoggerExtensions_InvalidLanguageIdFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_InvalidLanguageIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring invalid registry key name {RegistryKeyName}..
        /// </summary>
        internal static string ILoggerExtensions_InvalidRegistryKeyNameFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_InvalidRegistryKeyNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded SQL LocalDB API from {InstanceApiPath}..
        /// </summary>
        internal static string ILoggerExtensions_NativeApiLoadedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NativeApiLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load SQL LocalDB API from {InstanceApiPath}. Error: {ErrorCode}..
        /// </summary>
        internal static string ILoggerExtensions_NativeApiLoadFailedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NativeApiLoadFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SQL LocalDB API DLL {InstanceApiPath}..
        /// </summary>
        internal static string ILoggerExtensions_NativeApiNotFoundFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NativeApiNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB API was not loaded..
        /// </summary>
        internal static string ILoggerExtensions_NativeApiNotLoaded {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NativeApiNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded SQL LocalDB Instance API library {InstanceApiPath}..
        /// </summary>
        internal static string ILoggerExtensions_NativeApiUnloadedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NativeApiUnloadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB native API version to load was overridden by the user to {InstanceApiOverrideVersion}..
        /// </summary>
        internal static string ILoggerExtensions_NativeApiVersionOverriddenByUserFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NativeApiVersionOverriddenByUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL LocalDB API DLL path could be found..
        /// </summary>
        internal static string ILoggerExtensions_NoNativeApiFound {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NoNativeApiFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server LocalDB is not installed..
        /// </summary>
        internal static string ILoggerExtensions_NotInstalled {
            get {
                return ResourceManager.GetString("ILoggerExtensions_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured SQL LocalDB Instance API override version {InstanceApiOverrideVersion} cannot be found..
        /// </summary>
        internal static string ILoggerExtensions_OverrideVersionNotFoundFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_OverrideVersionNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open registry key {RegistryKeyName}..
        /// </summary>
        internal static string ILoggerExtensions_RegistryKeyNotFoundFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_RegistryKeyNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared SQL LocalDB instance {InstanceName} for owner SID {OwnerSid} as {SharedInstanceName}..
        /// </summary>
        internal static string ILoggerExtensions_SharedInstanceFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_SharedInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing SQL LocalDB instance {InstanceName} for owner SID {OwnerSid} as shared instance name {SharedInstanceName}..
        /// </summary>
        internal static string ILoggerExtensions_SharingInstanceFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_SharingInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started SQL LocalDB instance {InstanceName} using named pipe {NamedPipe}..
        /// </summary>
        internal static string ILoggerExtensions_StartedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StartedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing started for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_StartedTracing {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StartedTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting SQL LocalDB instance {InstanceName}..
        /// </summary>
        internal static string ILoggerExtensions_StartingFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StartingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting tracing for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_StartTracing {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StartTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop SQL LocalDB instance {InstanceName} with HRESULT {HResult}..
        /// </summary>
        internal static string ILoggerExtensions_StopFailedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StopFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped SQL LocalDB instance {InstanceName} after {Timeout}..
        /// </summary>
        internal static string ILoggerExtensions_StoppedFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped sharing SQL LocalDB instance {InstanceName}..
        /// </summary>
        internal static string ILoggerExtensions_StoppedSharingFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StoppedSharingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing stopped for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_StoppedTracing {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StoppedTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping SQL LocalDB instance {InstanceName} with timeout: {Timeout} and option(s) {StopOptions}..
        /// </summary>
        internal static string ILoggerExtensions_StoppingFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StoppingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping sharing SQL LocalDB instance {InstanceName}..
        /// </summary>
        internal static string ILoggerExtensions_StoppingSharingFormat {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StoppingSharingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping tracing for SQL LocalDB..
        /// </summary>
        internal static string ILoggerExtensions_StoppingTracing {
            get {
                return ResourceManager.GetString("ILoggerExtensions_StoppingTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified instance of {0} does not implement the {1} interface..
        /// </summary>
        internal static string ISqlLocalDbInstanceInfoExtensions_DoesNotImplementAdapterFormat {
            get {
                return ResourceManager.GetString("ISqlLocalDbInstanceInfoExtensions_DoesNotImplementAdapterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB instance &apos;{0}&apos; is not running..
        /// </summary>
        internal static string ISqlLocalDbInstanceInfoExtensions_NotRunningFormat {
            get {
                return ResourceManager.GetString("ISqlLocalDbInstanceInfoExtensions_NotRunningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred calling the SQL Server LocalDB with HRESULT {0:X}..
        /// </summary>
        internal static string SqlLocalDbApi_GenericFailureFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_GenericFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred calling the SQL Server LocalDB with HRESULT {HResult}..
        /// </summary>
        internal static string SqlLocalDbApi_LogGenericFailureFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogGenericFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL LocalDB returned HRESULT {HResult}..
        /// </summary>
        internal static string SqlLocalDbApi_NativeResultFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NativeResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL LocalDB instance name specified..
        /// </summary>
        internal static string SqlLocalDbApi_NoInstanceName {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NoInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logger was provided for the {0} instance..
        /// </summary>
        internal static string SqlLocalDbApi_NoLoggerFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NoLoggerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server LocalDB is not installed on {0}..
        /// </summary>
        internal static string SqlLocalDbApi_NotInstalledFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NotInstalledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions of SQL Server LocalDB are installed on {0}..
        /// </summary>
        internal static string SqlLocalDbApi_NoVersionsFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NoVersionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB Instance API is not supported on this platform..
        /// </summary>
        internal static string SqlLocalDbApi_PlatformNotSupported {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_PlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than TimeSpan.Zero..
        /// </summary>
        internal static string SqlLocalDbApi_TimeoutTooSmallFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_TimeoutTooSmallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enumerate the installed versions of SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbApi_VersionEnumerationFailed {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_VersionEnumerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with a SQL Server LocalDB instance..
        /// </summary>
        internal static string SqlLocalDbException_DefaultMessage {
            get {
                return ResourceManager.GetString("SqlLocalDbException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to share SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstanceManager_ShareFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstanceManager_ShareFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstanceManager_StartFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstanceManager_StartFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstanceManager_StopFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstanceManager_StopFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop sharing SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstanceManager_UnshareFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstanceManager_UnshareFailedFormat", resourceCulture);
            }
        }
    }
}
