//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.SqlLocalDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.SqlLocalDb.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified database file name is invalid: {0}.
        /// </summary>
        internal static string Extensions_InvalidPathFormat {
            get {
                return ResourceManager.GetString("Extensions_InvalidPathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current AppDomain has no value set for the Data Directory..
        /// </summary>
        internal static string Extensions_NoAppDomainDataDirectory {
            get {
                return ResourceManager.GetString("Extensions_NoAppDomainDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection string named &apos;{0}&apos; can be found in the application configuration file..
        /// </summary>
        internal static string Extensions_NoConnectionStringFormat {
            get {
                return ResourceManager.GetString("Extensions_NoConnectionStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection strings are configured in the application configuration file..
        /// </summary>
        internal static string Extensions_NoConnectionStrings {
            get {
                return ResourceManager.GetString("Extensions_NoConnectionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No named pipe is associated with the specified SQL LocalDB instance..
        /// </summary>
        internal static string Extensions_NoNamedPipe {
            get {
                return ResourceManager.GetString("Extensions_NoNamedPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one connection string is configured in the application configuration file.  The connection string name must be explicitly specified.  Other connection strings may be inherited from higher-level configuration files such as machine.config..
        /// </summary>
        internal static string Extensions_NoSingleConnectionString {
            get {
                return ResourceManager.GetString("Extensions_NoSingleConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an instance of type &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Logger_FailedToCreateCustomLoggerFormat {
            get {
                return ResourceManager.GetString("Logger_FailedToCreateCustomLoggerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB native API version to load was overridden by the user to {0}..
        /// </summary>
        internal static string NativeMethods_ApiVersionOverriddenByUserFormat {
            get {
                return ResourceManager.GetString("NativeMethods_ApiVersionOverriddenByUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB function {0} could not be found..
        /// </summary>
        internal static string NativeMethods_FunctionNotFoundFormat {
            get {
                return ResourceManager.GetString("NativeMethods_FunctionNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring invalid registry key name &apos;{0}&apos;..
        /// </summary>
        internal static string NativeMethods_InvalidRegistryKeyNameFormat {
            get {
                return ResourceManager.GetString("NativeMethods_InvalidRegistryKeyNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded SQL LocalDB API from &apos;{0}&apos;..
        /// </summary>
        internal static string NativeMethods_NativeApiLoadedFormat {
            get {
                return ResourceManager.GetString("NativeMethods_NativeApiLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load SQL LocalDB API from &apos;{0}&apos;. Error: {1}..
        /// </summary>
        internal static string NativeMethods_NativeApiLoadFailedFormat {
            get {
                return ResourceManager.GetString("NativeMethods_NativeApiLoadFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SQL LocalDB API DLL &apos;{0}&apos;..
        /// </summary>
        internal static string NativeMethods_NativeApiNotFoundFormat {
            get {
                return ResourceManager.GetString("NativeMethods_NativeApiNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB API was not loaded..
        /// </summary>
        internal static string NativeMethods_NativeApiNotLoaded {
            get {
                return ResourceManager.GetString("NativeMethods_NativeApiNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL LocalDB API DLL path could be found..
        /// </summary>
        internal static string NativeMethods_NoNativeApiFound {
            get {
                return ResourceManager.GetString("NativeMethods_NoNativeApiFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured SQL LocalDB Instance API override version &apos;{0}&apos; cannot be found on {1}..
        /// </summary>
        internal static string NativeMethods_OverrideVersionNotFoundFormat {
            get {
                return ResourceManager.GetString("NativeMethods_OverrideVersionNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open registry key &apos;{0}&apos;..
        /// </summary>
        internal static string NativeMethods_RegistryKeyNotFoundFormat {
            get {
                return ResourceManager.GetString("NativeMethods_RegistryKeyNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with SQL Server LocalDB. HRESULT = {0:X}.
        /// </summary>
        internal static string SqlLocalDbApi_GenericFailureFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_GenericFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL LocalDB instance &apos;{0}&apos; cannot be found so was not deleted..
        /// </summary>
        internal static string SqlLocalDbApi_InstanceDoesNotExistFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_InstanceDoesNotExistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current value ({0}) of the {1}.LanguageId property is not recognized by SQL LocalDB. Use a valid Windows Locale ID (LCID) or set the value to zero to use the Windows defaults..
        /// </summary>
        internal static string SqlLocalDbApi_InvalidLanguageIdFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_InvalidLanguageIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created named instance of SQL LocalDB. Instance name: &apos;{0}&apos;; version: &apos;{1}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogCreatedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogCreatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating named instance of SQL LocalDB. Instance name: &apos;{0}&apos;; version: &apos;{1}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogCreatingFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogCreatingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted named instance of SQL LocalDB &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogDeletedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogDeletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted file(s) for SQL LocalDB instance &apos;{0}&apos; from &apos;{1}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogDeletedInstanceFilesFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogDeletedInstanceFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB instance &apos;{0}&apos; could not be deleted as it is currently in use..
        /// </summary>
        internal static string SqlLocalDbApi_LogDeleteFailedAsInUseFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogDeleteFailedAsInUseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting named instance of SQL LocalDB &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogDeletingFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogDeletingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file(s) for SQL LocalDB instance &apos;{0}&apos; from &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string SqlLocalDbApi_LogDeletingInstanceFilesFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogDeletingInstanceFilesFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file(s) for SQL LocalDB instance &apos;{0}&apos; from &apos;{1}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogDeletingInstanceFilesFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogDeletingInstanceFilesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining instance names for SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbApi_LogGetInstances {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogGetInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining information for SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogGettingInfoFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogGettingInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining version information for SQL LocalDB version &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogGetVersionInfoFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogGetVersionInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained information for SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogGotInfoFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogGotInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained {0} instance names for SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbApi_LogGotInstancesFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogGotInstancesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained version information for SQL LocalDB version &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogGotVersionInfoFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogGotVersionInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL LocalDB returned HRESULT {0}..
        /// </summary>
        internal static string SqlLocalDbApi_LogNativeResultFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogNativeResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared SQL LocalDB instance &apos;{0}&apos; for owner SID &apos;{1}&apos; as &apos;{2}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogSharedInstanceFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogSharedInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing SQL LocalDB instance &apos;{0}&apos; for owner SID &apos;{1}&apos;. Shared instance name: &apos;{2}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogSharingInstanceFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogSharingInstanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started SQL LocalDB instance &apos;{0}&apos; using named pipe &apos;{1}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogStartedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStartedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing started for SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbApi_LogStartedTracing {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStartedTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogStartingFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStartingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting tracing for SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbApi_LogStartTracing {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStartTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped SQL LocalDB instance &apos;{0}&apos; after {1}..
        /// </summary>
        internal static string SqlLocalDbApi_LogStoppedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStoppedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped sharing SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogStoppedSharingFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStoppedSharingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing stopped for SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbApi_LogStoppedTracing {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStoppedTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping SQL LocalDB instance &apos;{0}&apos;. Timeout: {1}; Option(s): {2}..
        /// </summary>
        internal static string SqlLocalDbApi_LogStoppingFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStoppingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping sharing SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbApi_LogStoppingSharingFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStoppingSharingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping tracing for SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbApi_LogStoppingTracing {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_LogStoppingTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL LocalDB instance name specified..
        /// </summary>
        internal static string SqlLocalDbApi_NoInstanceName {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NoInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server LocalDB is not installed on {0}..
        /// </summary>
        internal static string SqlLocalDbApi_NotInstalledFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NotInstalledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions of SQL Server LocalDB are installed on {0}..
        /// </summary>
        internal static string SqlLocalDbApi_NoVersionsFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NoVersionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than TimeSpan.Zero..
        /// </summary>
        internal static string SqlLocalDbApi_TimeoutTooSmallFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_TimeoutTooSmallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with a SQL Server LocalDB instance..
        /// </summary>
        internal static string SqlLocalDbException_DefaultMessage {
            get {
                return ResourceManager.GetString("SqlLocalDbException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enumerate the installed versions of SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbException_VersionEnumerationFailed {
            get {
                return ResourceManager.GetString("SqlLocalDbException_VersionEnumerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL LocalDB instance &apos;{0}&apos; already exists..
        /// </summary>
        internal static string SqlLocalDbFactory_InstanceExistsFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbFactory_InstanceExistsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_DeleteFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_DeleteFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB instance &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SqlLocalDbInstance_InstanceNotFoundFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_InstanceNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB instance &apos;{0}&apos; is not running..
        /// </summary>
        internal static string SqlLocalDbInstance_NotRunningFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_NotRunningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to share SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_ShareFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_ShareFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_StartFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_StartFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_StopFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_StopFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop sharing SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_UnshareFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_UnshareFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL LocalDB instance returned by underlying SQL LocalDB API..
        /// </summary>
        internal static string SqlLocalDbProvider_NoInstance {
            get {
                return ResourceManager.GetString("SqlLocalDbProvider_NoInstance", resourceCulture);
            }
        }
    }
}
