//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.SqlLocalDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.SqlLocalDb.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with SQL Server LocalDB.  HRESULT = {0}.
        /// </summary>
        internal static string SqlLocalDbApi_GenericFailureFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_GenericFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL LocalDB instance name specified..
        /// </summary>
        internal static string SqlLocalDbApi_NoInstanceName {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NoInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server LocalDB is not installed on {0}..
        /// </summary>
        internal static string SqlLocalDbApi_NotInstalledFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NotInstalledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions of SQL Server LocalDB are installed on {0}..
        /// </summary>
        internal static string SqlLocalDbApi_NoVersionsFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_NoVersionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than TimeSpan.Zero..
        /// </summary>
        internal static string SqlLocalDbApi_TimeoutTooSmallFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbApi_TimeoutTooSmallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with a SQL Server LocalDB instance..
        /// </summary>
        internal static string SqlLocalDbException_DefaultMessage {
            get {
                return ResourceManager.GetString("SqlLocalDbException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enumerate the installed versions of SQL LocalDB..
        /// </summary>
        internal static string SqlLocalDbException_VersionEnumerationFailed {
            get {
                return ResourceManager.GetString("SqlLocalDbException_VersionEnumerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL LocalDB instance &apos;{0}&apos; already exists..
        /// </summary>
        internal static string SqlLocalDbFactory_InstanceExistsFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbFactory_InstanceExistsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_DeleteFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_DeleteFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB instance &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SqlLocalDbInstance_InstanceNotFoundFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_InstanceNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL LocalDB instance &apos;{0}&apos; is not running..
        /// </summary>
        internal static string SqlLocalDbInstance_NotRunningFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_NotRunningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to share SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_ShareFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_ShareFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_StartFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_StartFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_StopFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_StopFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop sharing SQL LocalDB instance &apos;{0}&apos;..
        /// </summary>
        internal static string SqlLocalDbInstance_UnshareFailedFormat {
            get {
                return ResourceManager.GetString("SqlLocalDbInstance_UnshareFailedFormat", resourceCulture);
            }
        }
    }
}
