name: GitHub CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build and test on Linux/macOS
      run: ./build.sh
      if: matrix.os != 'windows-latest'
      env:
        CI: true
    - name: Build and test on Windows
      run: .\Build.ps1
      shell: powershell
      if: matrix.os == 'windows-latest'
      env:
        CI: true
